language: node_js
node_js:
  - "node"
warnings_are_errors: false

install:
  - npm install

script:
  - npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "lkGz+qaFg7mZK0A8vhYOQz+ozKwyjLZQ/1nLe07ohYHD+7vqF0EyNfzvDH3O+kNCcErfP0UYid+2SXmlCwQi/KdNyWxlUWOUDJCizQT+COr+fvHYxBTYkyWzSZoMuMSDPSwHIUSdzELqpE0/rA8DOagLqurdiSWfMqC2n9yzpT9Oas92XEzNLBAw4doZoOi+T7mEuWFG1AQBWyk4BsjU5hSWyAzLWgudD7V9e9ujLl56IhMEK273pWFtOrUtn/MLXSYCDL6Lpl9eHXtzQEzSA9c0QMGkPnZQuBj9EXUvD8K/j4DYqFcwwm5ow2BeEKETzhGxrPvRLE2j7QbU1Txl/I/wwxODGJS74K+VSHbi+KKWdIdDk5KkdfvpsZ08WG5109FR3estYX3Kmbjob/P/nsRUNF2mDXauRKDE5J9Us8fjTJx3xB/HAijAbOX8b0bqvn97ESaOle4iLam/S+2VpVrn/vjP7R8l5OCaS2NDu25MTbYlwtkPwvCb3TLZwWjEBKnrhhY9uR4EQcHuqn422cUFoF5lxqGgnimwhBE9pJwLbSHvQ1YfqA3evnh0CxANWV4OGH15JQe9tzGJvHrqclx3wFnlUJ7hLN8gVv3n9ds1fTZVzI9r7e2ldI8LOly1QOqGmKHddyLOqvy93D4wppaa+kUvco8H9RBzv3o8KOo="
