language: node_js
node_js:
  - "node"
warnings_are_errors: false

install:
  - npm install

script:
  - npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "qvH4GoSwEDAZ7v0KLAG2+cyLZ/i/XVGmmcjhZofvxVJGeCa1PqRRojN0psFXOzBFGCJBmHpJ8ShmEmSyP5b2DEcgB6CTSR16z5yojQChPLBPive/6EnJzcEcQh/DCMXcWHCr4lsMSDAt/pcqA4+HDmgpXRhJPFWZrnyqnLltkmmIF42jsPI2lWwzQISDStNRtrksICbpaqkViOsi20WWO43h8Kzw62CzsZsjgthK70B/rPTRqaS4dbG5dlbpIN0E9BmZ109atWfJLwod7bwpJSExPZbCRrfrdMMQWHPrVdQAoGOFQKSeQDlChQy2u6mRg1X3cM3RUD9W73CCb+knoPy6pThn7+S3rMCYMwHrVAwjjVsxfiFNeJ4iDdZwHQcor0QV2LPiaKGgddgh3hBf38SfIMU4D4C9gdHEPWoqNnqtRXyiMLCJVEzC7IRL/A/ntTc+tzhZRuiIOmW8QCft7g86P25+V5XbMJGHSzwn65iHcY1VX7AJBuKXu0ju1apjRnNCqnXMtiUibo55VYvjdd0ighSxZkCNOAfOiQvPdrR4nHUNYuXOgACykfAI+3zyulEUbqe26G2WCdAFu7jEw1nfAZSJuvovCERjD2cJaHISw6y/D11bMSBD6zdD+AlLkPuIiTX1Z4+SzJYLxM680qkJJxKMjQyrhWz5JSlojvs="
